Player struct changes
javieralaves/Pachanga pull request #2
Opened 2023-08-01 17:33 UTC by javieralaves

2023-08-01 17:38 UTC, javieralaves commented on Pachanga/Player.swift
> +    // var wins: Int = 0
Commented these out for now as they're not needed

2023-08-02 10:20 UTC, Sn0wwy commented on Pachanga/Player.swift
> +    var sessions: [Session]
id should be given the type UUID and not initialised using UUID() since apple sign ins have their own initialised UUID

2023-08-02 10:20 UTC, Sn0wwy commented on Pachanga/Player.swift
> +    var sessions: [Session]
profileImage can be commented for now

2023-08-02 10:23 UTC, Sn0wwy requested changes
Consider changing var id = UUID() to var id : UUID for now since it might cause issues with apple log in.
profileImage might be better off commented for now.

2023-08-02 12:14 UTC, merged